# LICENSE UPL 1.0
#
# Copyright (c) 1982-2018 Oracle and/or its affiliates. All rights reserved.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Dockerfile for Oracle Database 18c Express Edition
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# None
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put the downloaded file in the same directory as this Dockerfile
# Run: 
#      $ docker build -t oracle/database:18.4.0-xe-slim -f Dockerfile.slim .
# Sample usage with init-db directory having an RMAN full backup:
#      $ docker run -ti --rm --name testdb -v /home/init-db:/opt/oracle/scripts/setup -v /run/shm:/dev/shm oracle/database:18.4.0-xe-slim
# passing init-db.tar.gz with a full RMAN backup initial db
#      $ docker run -ti --rm --name testdb -v /home/init-db.tar.gz:/opt/oracle/scripts/setup/init-db.tar.gz -v /run/shm:/dev/shm oracle/database:18.4.0-xe-slim
#
# Pull base image
# ---------------
FROM oracle/database:18.4.0-xe AS db-xe
FROM oraclelinux:7-slim AS baseOS

# Labels
# ------
LABEL "provider"="Oracle"                                               \
      "issues"="https://github.com/oracle/docker-images/issues"         \
      "volume.data"="/opt/oracle/oradata"                               \
      "volume.setup.location1"="/opt/oracle/scripts/setup"              \
      "volume.setup.location2"="/docker-entrypoint-initdb.d/setup"      \
      "volume.startup.location1"="/opt/oracle/scripts/startup"          \
      "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"  \
      "port.listener"="1521"                                            \
      "port.oemexpress"="5500"                                          \
      "port.apex"="8080"

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE \
    ORACLE_SID=XE \
    INSTALL_FILE_1="https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm" \
    RUN_FILE="runOracle-slim.sh" \
    PWD_FILE="setPassword.sh" \
    CLR_FILE="cleanup.sh" \
    CONF_FILE="oracle-xe-18c.conf" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    INSTALL_DIR="$HOME/install" \
    ORACLE_DOCKER_INSTALL="true"

# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$PATH

RUN yum -y install openssl file oracle-database-preinstall-18c && \
    rm -rf /var/cache/yum

FROM baseOS AS baseInstall
# Copy Oracle XE installation
# -------------
COPY $CLR_FILE $INSTALL_DIR/

COPY --from=db-xe --chown=oracle:oinstall $ORACLE_BASE/ $ORACLE_BASE/
COPY --from=db-xe --chown=oracle:oinstall /etc/oratab /etc/oratab
COPY --from=db-xe --chown=root:root /etc/init.d/oracle-xe-18c /etc/init.d/oracle-xe-18c
COPY --from=db-xe --chown=root:root /etc/sysconfig/$CONF_FILE /etc/sysconfig/$CONF_FILE
COPY --from=db-xe --chown=root:root /opt/ORCLfmap /opt/ORCLfmap

RUN chmod +x $INSTALL_DIR/$CLR_FILE && \
    $INSTALL_DIR/$CLR_FILE

FROM baseOS

COPY --from=baseInstall $ORACLE_BASE/ $ORACLE_BASE/
COPY --from=baseInstall /etc/oratab /etc/oratab
COPY --from=baseInstall /etc/init.d/oracle-xe-18c /etc/init.d/oracle-xe-18c
COPY --from=baseInstall /etc/sysconfig/$CONF_FILE /etc/sysconfig/$CONF_FILE
COPY --from=baseInstall /opt/ORCLfmap /opt/ORCLfmap
COPY $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CONF_FILE $ORACLE_BASE/

RUN mkdir -p /home/oracle && \
    chown -R oracle:oinstall /home/oracle && \
    chown oracle:oinstall $ORACLE_BASE && \
    sed -i -r 's/^(session\s+required\s+pam_limits.so)/#\1/' /etc/pam.d/* && \
    ln -s $ORACLE_BASE/$PWD_FILE / && \
    rm -rf /var/lib/rpm/* && \
    rm -rf /var/log/* && \
    ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d && \
    cd $HOME && \
    chmod ug+x $ORACLE_BASE/*.sh

VOLUME ["$ORACLE_BASE/oradata"]
EXPOSE 1521 8080 5500
HEALTHCHECK --interval=1m --start-period=20m \
   CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1

CMD exec $ORACLE_BASE/$RUN_FILE
